name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*
env:
  IMAGE_NAME: chef-bot
  REGISTRY: ghcr.io
  DOCKERDEPLOY_HOST_USER: ${{secrets.DOCKERDEPLOY_HOST_USER }}
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - 
        name: Calculate Publishing Variables
        run: |
          # docker.pkg.github.com/
          IMAGE_ID=${{ github.repository }}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=0.1.${{github.run_number}}

          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "CURRENT_ID=ghcr.io/$IMAGE_ID" >> $GITHUB_ENV

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"

          echo ${#DOCKERDEPLOY_HOST_USER}
          echo -n "$DOCKERDEPLOY_HOST_USER" | wc -c
          echo -n "${{env.DOCKERDEPLOY_HOST_USER }}" | wc -c
          echo -n "${{secrets.DOCKERDEPLOY_HOST_USER }}" | wc -c
      - 
        name: Build Bot
        run: docker build -t chefbot .
      - 
        name: Echoing the publishing Variables
        run: |
          echo IMAGE_ID="${{env.IMAGE_ID}}"
          echo VERSION="${{env.VERSION}}"
      - 
        name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - 
        name: Push chefbot image
        run: |
          CURRENT_ID=ghcr.io/$IMAGE_ID
          docker tag chefbot $CURRENT_ID:$VERSION
          docker tag chefbot $CURRENT_ID:latest

          docker push $CURRENT_ID:$VERSION
          docker push $CURRENT_ID:latest
      - 
        name: Deploy to Server via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.DOCKERDEPLOY_HOST }}
          USERNAME: ${{ secrets.DOCKERDEPLOY_HOST_USER }}
          port: ${{ secrets.DOCKERDEPLOY_HOST_PORT }}
          KEY: ${{ secrets.DOCKERDEPLOY_PK }}
          envs: ${{ env.CURRENT_ID }}
          script: |
            cd /root/dockerbots/chef-bot
            echo "${{secrets.PUBLISH_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker stop $(docker ps -q -f "name=chef-bot") && docker container rm -f chef-bot || echo "No container to stop"
            docker pull "${{ env.CURRENT_ID }}:latest" && docker run -d --name=chef-bot --env Discord__BotToken=${{ secrets.BOT_TOKEN }} --restart=unless-stopped ${{ env.CURRENT_ID }}:latest
